from dataclasses import dataclass
from typing import Protocol


class LeaseLost(RuntimeError):
    pass


@dataclass(frozen=True)
class Job:
    id: int
    lecture_id: int
    token: str
    attempts: int


class JobQueue(Protocol):
    """At-least-once delivery; adapters also project status/run_token to lectures.

    run_token fences checkpoint writes independently of the broker. A future
    Redis adapter must preserve this contract, global capacity and lease checks.
    """

    async def enqueue(self, lecture_id: int) -> None: ...
    async def reconcile(self) -> None: ...
    async def recover_after_supervisor_restart(self) -> dict[str, int]: ...
    async def claim(self, worker_id: str) -> Job | None: ...
    async def heartbeat(self, job: Job) -> bool: ...
    async def assign_gpu(self, job: Job, gpu_id: str) -> bool: ...
    async def owns(self, job: Job) -> bool: ...
    async def finish(self, job: Job) -> bool: ...
    async def fail(self, job: Job, error: str, *, retryable: bool) -> bool: ...
    async def release(self, job: Job) -> bool: ...
    async def pause_for_review(self, job: Job) -> bool: ...
    async def resume_review(self, lecture_id: int) -> bool: ...
    async def cancel(self, lecture_id: int) -> bool: ...
    async def retry(self, lecture_id: int) -> bool: ...
    async def record_error(self, job: Job, error: str) -> None: ...
    async def last_error(self, job: Job) -> str: ...
